# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  name: Default # Replace with 'vmImage: windows-latest' for a Microsoft-hosted agent if needed

steps:
  - script: |
      echo JAVA_HOME=%JAVA_HOME%
      echo PATH=%PATH%
      java -version
      mvn -version
    displayName: 'Debug Environment'

  - script: echo "My first Azure Pipeline for Maven project"
    displayName: 'Run a one-line script'

  - task: Maven@4
    displayName: 'Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11' # Adjust based on your project
      mavenVersionOption: 'Default'

  - script: java -jar target/Sample1-1.0-SNAPSHOT.jar
    displayName: 'Run the JAR file'